//this file is generated by python script mkurom.py.
//Do not edit under pain of losing your edits!

module ID__ 
 # (UIP_WIDTH=4)
( 
      input logic [6:0] opcode,
      output logic [UIP_WIDTH-1:0] uip 
            ); 
always_comb begin
  unique case (opcode) inside
    7'h00 :  uip = 4'd0 ;   // NOP
    7'h01 :  uip = 4'd8 ;   // ADD
    default:      uip = 4'd9 ;   // #UD fault
  endcase
end
endmodule  // ID__ 
