//this file is generated by python script mkurom.py.
//Do not edit under pain of losing your edits!

module US__ ( 
      input logic [2:0] uip,
      output logic [20:0] sig 

          );
always_comb begin
  unique case ( uip ) 
// ==== INSTRUCTION: SW ====
    3'd0: sig = 21'b100000000000000000000; // dummy
    default: sig = 21'd0;
  endcase
end
endmodule // US__ 
