//this file is generated by python script mkurom.py.
//Do not edit under pain of losing your edits!

module US__ ( 
      input logic [2:0] uip,
      output logic [16:0] sig 

          );
always_comb begin
  unique case ( uip ) 
// ==== INSTRUCTION: NOP ====
    3'd0: sig = 17'b10000000000000000; // dummy
// ==== INSTRUCTION: ADD ====
    3'd1: sig = 17'b10000000000000000; // dummy
// ==== LABEL: UD_fault ====
    3'd2: sig = 17'b10000000000000000; // dummy
    default: sig = 17'd0;
  endcase
end
endmodule // US__ 
